require('dotenv').config()

module.exports = {
	env: {
		// Reference a variable that was defined in the .env file and make it available at Build Time
		GRAPHQL_URI: process.env.GRAPHQL_URI,
		REFRESH_TOKEN_URL: process.env.REFRESH_TOKEN_URL,
		FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
		FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
		FIREBASE_DATABASE_URL: process.env.FIREBASE_DATABASE_URL,
		FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
		FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
		FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
		FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
		FIREBASE_AUTH_REDIRECT_URL: process.env.FIREBASE_AUTH_REDIRECT_URL,
		FIREBASE_REFRESH_TOKEN_URL: process.env.FIREBASE_REFRESH_TOKEN_URL
	},
}